### ISSUE TITLE
error with file access when generating individual stats

### ISSUE THREAD

**Issue by sfspear2** [thierrygosselin/radiator#75] opened 2020-02-27 12:46 UTC
I am trying to run the below code and running into an error when it is trying to generate individual stats that the program is trying to access a file in use.  The input files used in this test were from a colleague and he confirmed he was able to run it with no errors. Thanks for your help.

> read.table("population_assign_radiator.txt", header=T)->strata
> 
> tidy_genomic_data("guttatus_new.vcf", vcf.metadata = F, strata=strata)->P_guttatus
################################################################################
################################################################################
Execution date@time: 20200227@0638
Folder created: 02_radiator_tidy_genomic_20200227@0638
Function call and arguments stored in: radiator_tidy_genomic_data_args_20200227@0638.tsv
Analyzing strata file
    Number of strata: 3
    Number of individuals: 79
Importing and tidying the VCF...
Execution date@time: 20200227@0638

Reading VCF
Data summary: 
    number of samples: 79
    number of markers: 4010
done! timing: 0 sec

Filter monomorphic markers
Number of individuals / strata / chrom / locus / SNP:
    Blacklisted: 0 / 0 / 238 / 238 / 238

Filter common markers:
Number of individuals / strata / chrom / locus / SNP:
    Blacklisted: 0 / 0 / 32 / 32 / 32
Generating individual stats...
Error in .DynamicClusterCall(cl, length(cl), .fun = function(.proc_idx,  : 
  One of the nodes produced an error: Can not open file 'C:\wilds\Thamnophis\radiator_test\02_radiator_tidy_genomic_20200227@0638\radiator_20200227@0638.gds'. The process cannot access the file because it is being used by another process.

Computation time, overall: 10 sec

Computation time, overall: 17 sec
############################## completed tidy_vcf ##############################

Computation time, overall: 18 sec
######################### completed tidy_genomic_data ##########################
> 
> write_bayescan(data = P_guttatus, filename = "P_guttatus_pops")
Generating BayeScan file...
Error in write_bayescan(data = P_guttatus, filename = "P_guttatus_pops") : 
  object 'P_guttatus' not found

**Comment by thierrygosselin** [comment] 2020-02-27 12:53
Dear sfspear2,

For me this issue makes the bug not reproducible and from the quick look of it, looks like a parallel processing problem associated with your PC (I assume here it's a PC because of the directory).

It could be because you don't have enough cores or that the R you installed doesn't work properly with parallel processing (the list is long with PC and I offer no support for this).

1. use `parallel.core = 1` it might be very long depending on the size of the dataset, but you'll have your answer.

2. if you still have a problem please read twice the guidelines for submitting an issue otherwise I'll have to close it because I won't be able to reproduce it.

Best
Thierry

**Closed by thierrygosselin** 2020-02-27 12:53 UTC

**Comment by sfspear2** [comment] 2020-02-27 13:19
Thank you – that was the issue. I’ll figure out why that’s the case with my machine, but I appreciate your time.

Stephen Spear, PhD
Director of Wildlife Ecology
The Wilds

14000 International Road              Office: 740.638.5030 ext. 2301<tel:(740)%20638-5030>
Cumberland OH  43732                   Fax: 740.638.2287<tel:(740)%20638-2287>
sspear@thewilds.org<mailto:sspear@thewilds.org>

[cid:image003.png@01D5ED3C.D544E360]
