### ISSUE TITLE
Issues with 'genomic_converter()'

### ISSUE THREAD

**Issue by RyanFranckowiak** [thierrygosselin/radiator#45] opened 2019-03-23 17:08 UTC
I am trying to convert a vcf file to another format i.e., genind. The program recognizes the files and identifies the correct number of individuals and snps but fail to complete the converstion. I keep receiving the following message:

Error in .DynamicClusterCall(cl, length(cl), .fun = function(.proc_idx, : One of the nodes produced an error: Can not open file 'C:\Users\Documents\Data_Analysis\134_radiator_genomic_converter_20190323@1302\radiator_20190323@1302.gds'. The process cannot access the file because it is being used by another process.

**Comment by thierrygosselin** [comment] 2019-03-24 00:08
**It's impossible with what your giving me to reproduce.**

- you need to give more info
- full command used (with arguments, values, etc)
- return the output of `devtools::session_info()` on a clean session, that might also help a bit on the parallelization part.
- Number of samples, populations and samples per pop would help or 
- Files used or part small part of it (if they are big)

Cheers
Thierry

**Comment by thierrygosselin** [comment] 2019-03-25 17:37
Feel free to reopen the issue if the problem is not fixed with my suggestions
Cheers

**Closed by thierrygosselin** 2019-03-25 17:37 UTC

**Comment by RyanFranckowiak** [comment] 2019-03-25 23:24
Thank you for your advice. I suspect the problem is the virus protection software on my computer which is preventing the files writing to the folder. I have found another work around. I will keep working on it to see if I can resolve the issue on my end. Thanks again. Best Ryan
________________________________
