### ISSUE TITLE
genomic_converter error

### ISSUE THREAD

**Issue by SebassArg** [thierrygosselin/radiator#103] opened 2020-12-03 17:20 UTC
Got an error converting bed on genind object. 
I did same convesrion before.
Now its not working

 AMOVA<-genomic_converter("Goat-HL.bed",  
+                          parallel.core = 8, output = "genind"
+                          ,filename = "G3 CART")$genind
################################################################################
################################################################################
Execution date@time: 20201203@1352
Folder created: 02_radiator_genomic_converter_20201203@1352
Function call and arguments stored in: radiator_genomic_converter_args_20201203@1352.tsv
Filters parameters file generated: filters_parameters_20201203@1352.tsv

Importing data: plink.bed.file
Reading PLINK bed file...

Data summary: 
    number of samples: 421
    number of markers: 50619

################################## IMPORTANT ###################################
Tidying PLINK file with 50619 SNPs is not optimal:
    1. a computer with lots of RAM is required
    2. it's very slow to generate
    3. it's very slow to run codes after
    4. for most non model species this number of markers is not realistic...

Recommendation:
    1. filter your dataset. e.g. with filter_rad

Ideally target a maximum of ~ 10 000 - 20 0000 unlinked SNPs

Genotypes formats generated with 50619 SNPs: 
    GT_BIN (the dosage of ALT allele: 0, 1, 2 NA)

Computation time, overall: 13 sec

Writing tidy data set:
G3 CART.rad

Preparing data for output

Data is bi-allelic

IMPORTANT genind object related question...
you have > 20 000 markers (50335)
Do you want the more suitable genlight object instead ? (y/n):

Continue working on genind object
Generating adegenet genind object
**Error in UseMethod("rename_") : 
  no applicable method for 'rename_' applied to an object of class "c('standardGeneric', 'genericFunction', 'function', 'OptionalFunction', 'PossibleMethod', 'expression_OR_function', 'optionalMethod')"
In addition: Warning message:
`rename_()` is deprecated as of dplyr 0.7.0.
Please use `rename()` instead.
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated.** 

Computation time, overall: 491 sec
######################### completed genomic_converter ##########################

- Session info ----------------------------------------------------------------------------
 setting  value                       
 version  R version 4.0.3 (2020-10-10)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_United States.1252  
 ctype    English_United States.1252  
 tz       America/Buenos_Aires        
 date     2020-12-03                  

- Packages --------------------------------------------------------------------------------
 package          * version  date       lib source                                   
 ade4             * 1.7-16   2020-10-28 [1] CRAN (R 4.0.3)                           
 adegenet         * 2.1.3    2020-05-10 [1] CRAN (R 4.0.3)                           
 ape                5.4-1    2020-08-13 [1] CRAN (R 4.0.3)                           
 assertthat         0.2.1    2019-03-21 [1] CRAN (R 4.0.3)                           
 BiocGenerics       0.36.0   2020-10-27 [1] Bioconductor                             
 Biostrings         2.58.0   2020-10-27 [1] Bioconductor                             
 bitops             1.0-6    2013-08-17 [1] CRAN (R 4.0.3)                           
 boot               1.3-25   2020-04-26 [2] CRAN (R 4.0.3)                           
 callr              3.5.1    2020-10-13 [1] CRAN (R 4.0.3)                           
 class              7.3-17   2020-04-26 [2] CRAN (R 4.0.3)                           
 classInt           0.4-3    2020-04-07 [1] CRAN (R 4.0.3)                           
 cli                2.2.0    2020-11-20 [1] CRAN (R 4.0.3)                           
 cluster            2.1.0    2019-06-19 [2] CRAN (R 4.0.3)                           
 coda               0.19-4   2020-09-30 [1] CRAN (R 4.0.3)                           
 codetools          0.2-16   2018-12-24 [2] CRAN (R 4.0.3)                           
 colorspace         2.0-0    2020-11-11 [1] CRAN (R 4.0.3)                           
 crayon             1.3.4    2017-09-16 [1] CRAN (R 4.0.3)                           
 data.table       * 1.13.2   2020-10-19 [1] CRAN (R 4.0.3)                           
 DBI                1.1.0    2019-12-15 [1] CRAN (R 4.0.3)                           
 deldir             0.2-3    2020-11-09 [1] CRAN (R 4.0.3)                           
 desc               1.2.0    2018-05-01 [1] CRAN (R 4.0.3)                           
 devtools           2.3.2    2020-09-18 [1] CRAN (R 4.0.3)                           
 digest             0.6.27   2020-10-24 [1] CRAN (R 4.0.3)                           
 dplyr            * 1.0.2    2020-08-18 [1] CRAN (R 4.0.3)                           
 e1071              1.7-4    2020-10-14 [1] CRAN (R 4.0.3)                           
 ellipsis           0.3.1    2020-05-15 [1] CRAN (R 4.0.3)                           
 expm               0.999-5  2020-07-20 [1] CRAN (R 4.0.3)                           
 fansi              0.4.1    2020-01-08 [1] CRAN (R 4.0.3)                           
 fastmap            1.0.1    2019-10-08 [1] CRAN (R 4.0.3)                           
 fastmatch          1.1-0    2017-01-28 [1] CRAN (R 4.0.3)                           
 fs                 1.5.0    2020-07-31 [1] CRAN (R 4.0.3)                           
 fst                0.9.4    2020-08-27 [1] CRAN (R 4.0.3)                           
 gdata              2.18.0   2017-06-06 [1] CRAN (R 4.0.3)                           
 gdsfmt             1.26.0   2020-10-27 [1] Bioconductor                             
 generics           0.1.0    2020-10-31 [1] CRAN (R 4.0.3)                           
 GenomeInfoDb       1.26.1   2020-11-20 [1] Bioconductor                             
 GenomeInfoDbData   1.2.4    2020-11-23 [1] Bioconductor                             
 GenomicRanges      1.42.0   2020-10-27 [1] Bioconductor                             
 ggplot2            3.3.2    2020-06-19 [1] CRAN (R 4.0.3)                           
 glue               1.4.2    2020-08-27 [1] CRAN (R 4.0.3)                           
 gmodels            2.18.1   2018-06-25 [1] CRAN (R 4.0.3)                           
 gtable             0.3.0    2019-03-25 [1] CRAN (R 4.0.3)                           
 gtools             3.8.2    2020-03-31 [1] CRAN (R 4.0.3)                           
 hms                0.5.3    2020-01-08 [1] CRAN (R 4.0.3)                           
 htmltools          0.5.0    2020-06-16 [1] CRAN (R 4.0.3)                           
 httpuv             1.5.4    2020-06-06 [1] CRAN (R 4.0.3)                           
 igraph             1.2.6    2020-10-06 [1] CRAN (R 4.0.3)                           
 IRanges            2.24.0   2020-10-27 [1] Bioconductor                             
 KernSmooth         2.23-17  2020-04-26 [2] CRAN (R 4.0.3)                           
 later              1.1.0.1  2020-06-05 [1] CRAN (R 4.0.3)                           
 lattice            0.20-41  2020-04-02 [2] CRAN (R 4.0.3)                           
 LearnBayes         2.15.1   2018-03-18 [1] CRAN (R 4.0.3)                           
 lifecycle          0.2.0    2020-03-06 [1] CRAN (R 4.0.3)                           
 magrittr           2.0.1    2020-11-17 [1] CRAN (R 4.0.3)                           
 MASS               7.3-53   2020-09-09 [2] CRAN (R 4.0.3)                           
 Matrix             1.2-18   2019-11-27 [2] CRAN (R 4.0.3)                           
 memoise            1.1.0    2017-04-21 [1] CRAN (R 4.0.3)                           
 mgcv               1.8-33   2020-08-27 [2] CRAN (R 4.0.3)                           
 mime               0.9      2020-02-04 [1] CRAN (R 4.0.3)                           
 munsell            0.5.0    2018-06-12 [1] CRAN (R 4.0.3)                           
 nlme               3.1-149  2020-08-23 [2] CRAN (R 4.0.3)                           
 operators        * 0.1-8    2015-07-11 [1] CRAN (R 4.0.3)                           
 pegas              0.14     2020-09-16 [1] CRAN (R 4.0.3)                           
 permute            0.9-5    2019-03-12 [1] CRAN (R 4.0.3)                           
 phangorn           2.5.5    2019-06-19 [1] CRAN (R 4.0.3)                           
 pillar             1.4.7    2020-11-20 [1] CRAN (R 4.0.3)                           
 pkgbuild           1.1.0    2020-07-13 [1] CRAN (R 4.0.3)                           
 pkgconfig          2.0.3    2019-09-22 [1] CRAN (R 4.0.3)                           
 pkgload            1.1.0    2020-05-29 [1] CRAN (R 4.0.3)                           
 plyr               1.8.6    2020-03-03 [1] CRAN (R 4.0.3)                           
 polysat            1.7-4    2019-03-06 [1] CRAN (R 4.0.3)                           
 poppr            * 2.8.6    2020-06-02 [1] CRAN (R 4.0.3)                           
 prettyunits        1.1.1    2020-01-24 [1] CRAN (R 4.0.3)                           
 processx           3.4.5    2020-11-30 [1] CRAN (R 4.0.3)                           
 progress           1.2.2    2019-05-16 [1] CRAN (R 4.0.3)                           
 promises           1.1.1    2020-06-09 [1] CRAN (R 4.0.3)                           
 ps                 1.4.0    2020-10-07 [1] CRAN (R 4.0.3)                           
 purrr              0.3.4    2020-04-17 [1] CRAN (R 4.0.3)                           
 quadprog           1.5-8    2019-11-20 [1] CRAN (R 4.0.3)                           
 R6                 2.5.0    2020-10-28 [1] CRAN (R 4.0.3)                           
 radiator         * 1.1.8    2020-12-03 [1] Github (thierrygosselin/radiator@c840001)
 raster             3.4-5    2020-11-14 [1] CRAN (R 4.0.3)                           
 Rcpp               1.0.5    2020-07-06 [1] CRAN (R 4.0.3)                           
 RCurl              1.98-1.2 2020-04-18 [1] CRAN (R 4.0.3)                           
 readr              1.4.0    2020-10-05 [1] CRAN (R 4.0.3)                           
 remotes            2.2.0    2020-07-21 [1] CRAN (R 4.0.3)                           
 reshape2           1.4.4    2020-04-09 [1] CRAN (R 4.0.3)                           
 rlang              0.4.9    2020-11-26 [1] CRAN (R 4.0.3)                           
 rprojroot          2.0.2    2020-11-15 [1] CRAN (R 4.0.3)                           
 rstudioapi         0.13     2020-11-12 [1] CRAN (R 4.0.3)                           
 S4Vectors          0.28.0   2020-10-27 [1] Bioconductor                             
 scales             1.1.1    2020-05-11 [1] CRAN (R 4.0.3)                           
 SeqArray           1.30.0   2020-10-28 [1] Bioconductor                             
 seqinr             4.2-4    2020-10-10 [1] CRAN (R 4.0.3)                           
 sessioninfo        1.1.1    2018-11-05 [1] CRAN (R 4.0.3)                           
 sf                 0.9-6    2020-09-13 [1] CRAN (R 4.0.3)                           
 shiny              1.5.0    2020-06-23 [1] CRAN (R 4.0.3)                           
 sp                 1.4-4    2020-10-07 [1] CRAN (R 4.0.3)                           
 spData             0.3.8    2020-07-03 [1] CRAN (R 4.0.3)                           
 spdep              1.1-5    2020-06-29 [1] CRAN (R 4.0.3)                           
 stringi            1.5.3    2020-09-09 [1] CRAN (R 4.0.3)                           
 stringr            1.4.0    2019-02-10 [1] CRAN (R 4.0.3)                           
 testthat           3.0.0    2020-10-31 [1] CRAN (R 4.0.3)                           
 tibble             3.0.4    2020-10-12 [1] CRAN (R 4.0.3)                           
 tidyr              1.1.2    2020-08-27 [1] CRAN (R 4.0.3)                           
 tidyselect         1.1.0    2020-05-11 [1] CRAN (R 4.0.3)                           
 units              0.6-7    2020-06-13 [1] CRAN (R 4.0.3)                           
 usethis            1.6.3    2020-09-17 [1] CRAN (R 4.0.3)                           
 vctrs              0.3.5    2020-11-17 [1] CRAN (R 4.0.3)                           
 vegan              2.5-7    2020-11-28 [1] CRAN (R 4.0.3)                           
 withr              2.3.0    2020-09-22 [1] CRAN (R 4.0.3)                           
 xtable             1.8-4    2019-04-21 [1] CRAN (R 4.0.3)                           
 XVector            0.30.0   2020-10-28 [1] Bioconductor                             
 zlibbioc           1.36.0   2020-10-28 [1] Bioconductor                             

[1] C:/Users/Sebass/Documents/R/win-library/4.0
[2] C:/Program Files/R/R-4.0.3/library

THANKS!!!

**Comment by thierrygosselin** [comment] 2020-12-03 17:35
Dear SebassArg, sorry about the bug you're experiencing with radiator.
I'll have a look at this today

Best,
Thierry

**Comment by cgraham13** [comment] 2020-12-10 19:55
Hey Thierry,

Was there a fix for this issue? I am experiencing the same issue after updating some packages today.

Hope you're doing well!

Carly

**Comment by thierrygosselin** [comment] 2020-12-12 18:39
The problem was with a deprecated argument from dplyr it's now fixed and will be in the next release today (v. 1.1.9).

I didn't have your dataset, so it's only tested on mine. Let me know if you still have a problem.

Please take into account the message produced above, about the number of markers.

Cheers,
Thierry

**Comment by thierrygosselin** [comment] 2020-12-12 20:51
Keep in mind that tidying large dataset requires more computer memory because R needs to access it. The use of GDS with SeqArray alleviate this problem.

My PLINK dataset of 6000 samples and 60 000 SNPs requires close to 20GB of memory RAM

**Comment by SebassArg** [comment] 2020-12-13 16:28
Thanks Thierry
We are running radiator in a server with 750gb RAM 
I think it should work... HAHA
We are trying to find an optimal filetered dataset.
Thanks again for radiator!!!

**Comment by cgraham13** [comment] 2020-12-14 21:26
Hey Thierry,

Thanks for the updated package, seems to fix the issue. Unfortunately I am running into another issue now when I am trying to use genomic_converter() to convert to a vcf file. I don't get this issue when converting to a genind or genepop.

> tidyvcf <- tidy_genomic_data(
+   data = "m3M3n3r70-NoPops.vcf",
+   strata = strata$strata,
+   verbose = FALSE,
+   parallel.core = 4,
+   vcf.metadata = FALSE,
+   blacklist.id = "m3M3n3r70-blacklist.id.missing.70.tsv",
+   filter.common.markers = TRUE
+ )
File written: strata_radiator_filtered_20201214@1519.tsv

Reading VCF... 

Data summary: 
    number of samples: 511
    number of markers: 3173

Filter monomorphic markers
Number of individuals / strata / chrom / locus / SNP:
    Blacklisted: 0 / 0 / 0 / 0 / 0

Filter common markers:
Number of individuals / strata / chrom / locus / SNP:
    Blacklisted: 0 / 0 / 0 / 30 / 30

Generating individual stats...
Generating markers stats...

Number of chromosome/contig/scaffold: 1
Number of locus: 3143
Number of markers: 3143
Number of strata: 22
Number of individuals: 481

Number of ind/strata:
LH = 128
LR = 20
B = 19
DL = 20
WL = 12
NL = 20
NeL = 7
LML = 6
McL = 15
KL = 5
RL = 14
LS = 33
BL = 6
JL = 17
ScL = 14
SaL = 18
LW = 20
GL = 14
SIL = 20
SeL = 17
LM = 40
LD = 16

Number of duplicate id: 0
radiator Genomic Data Structure (GDS) file: radiator_20201214@1519.gds

Genotypes formats generated with 3143 SNPs: 
    GT_BIN (the dosage of ALT allele: 0, 1, 2 NA): TRUE
    GT_VCF (the genotype coding VCFs: 0/0, 0/1, 1/1, ./.): TRUE
    GT_VCF_NUC (the genotype coding in VCFs, but with nucleotides: A/C, ./.): TRUE
    GT (the genotype coding 'a la genepop': 001002, 001001, 000000): TRUE

Tidy data file written: radiator_20201214@1519.rad

Computation time, overall: 20 sec
Warning messages:
1: Unknown or uninitialised column: `COVERAGE_TOTAL`. 
2: In mean.default(id.stats$COVERAGE_TOTAL, na.rm = TRUE) :
  argument is not numeric or logical: returning NA
3: Unknown or uninitialised column: `COVERAGE_MEAN`. 
4: In mean.default(id.stats$COVERAGE_MEAN, na.rm = TRUE) :
  argument is not numeric or logical: returning NA
5: Unknown or uninitialised column: `COVERAGE_MEAN`. 
6: In mean.default(markers.stats$COVERAGE_MEAN, na.rm = TRUE) :
  argument is not numeric or logical: returning NA
> LocalAdapt.genind <- genomic_converter(
+   data = tidyvcf,
+   strata = strata$strata,
+   output = c("genind", "vcf"), 
+   blacklist.id = "m3M3n3r70-blacklist.id.missing.70.tsv",
+   vcf.metadata = FALSE,
+   #verbose = FALSE,
+   filter.common.markers = TRUE,
+   parallel.core = 4
+ )
################################################################################
######################### radiator::genomic_converter ##########################
################################################################################
Execution date@time: 20201214@1522
Folder created: -469_radiator_genomic_converter_20201214@1522
Function call and arguments stored in: radiator_genomic_converter_args_20201214@1522.tsv
Filters parameters file generated: filters_parameters_20201214@1522.tsv

Importing data: tbl_df
File written: strata_radiator_filtered_20201214@1522.tsv
Synchronizing data and strata...
    Number of strata: 22
    Number of individuals: 481

Writing tidy data set:
radiator_data_20201214@1522.rad

Preparing data for output

Data is bi-allelic
Generating adegenet genind object
Generating VCF file
Calibrating REF/ALT alleles...
Error: Can't subset columns that don't exist.
x Column `GT_VCF` doesn't exist.
Run `rlang::last_error()` to see where the error occurred.

Computation time, overall: 29 sec
######################### completed genomic_converter ##########################


> rlang::last_error()
<error/vctrs_error_subscript_oob>
Can't subset columns that don't exist.
x Column `GT_VCF` doesn't exist.
Backtrace:
  1. radiator::genomic_converter(...)
  2. radiator::write_vcf(data = input, filename = filename)
 12. dplyr:::select.data.frame(.data = data, MARKERS, GT_VCF)
 13. tidyselect::eval_select(expr(c(...)), .data)
 14. tidyselect:::eval_select_impl(...)
 22. tidyselect:::vars_select_eval(...)
 23. tidyselect:::walk_data_tree(expr, data_mask, context_mask)
 24. tidyselect:::eval_c(expr, data_mask, context_mask)
 25. tidyselect:::reduce_sels(node, data_mask, context_mask, init = init)
 26. tidyselect:::walk_data_tree(new, data_mask, context_mask)
 27. tidyselect:::as_indices_sel_impl(...)
 28. tidyselect:::as_indices_impl(x, vars, strict = strict)
 29. tidyselect:::chr_as_locations(x, vars)
 30. vctrs::vec_as_location(x, n = length(vars), names = vars)
 32. vctrs:::stop_subscript_oob(...)
 33. vctrs:::stop_subscript(...)

**Comment by thierrygosselin** [comment] 2020-12-14 21:41
definitely a bug, will try to fix today

**Comment by tpfeilsticker** [comment] 2021-01-06 06:23
Hi Thierry,

I'm running into a similar error when using write.genepop to save a genepop file from a tidy file:

write_genepop(t_genpop, pop.levels = NULL)
Calibrating REF/ALT alleles...
Error: Can't subset columns that don't exist.
x Column `GT` doesn't exist.

rlang::last_error()
<error/vctrs_error_subscript_oob>
Can't subset columns that don't exist.
x Column `GT` doesn't exist.
Backtrace:
  1. radiator::write_genepop(t_genpop, pop.levels = NULL)
  4. dplyr:::select.data.frame(., POP_ID, INDIVIDUALS, MARKERS, GT)
  5. tidyselect::eval_select(expr(c(...)), .data)
  6. tidyselect:::eval_select_impl(...)
 14. tidyselect:::vars_select_eval(...)
 15. tidyselect:::walk_data_tree(expr, data_mask, context_mask)
 16. tidyselect:::eval_c(expr, data_mask, context_mask)
 17. tidyselect:::reduce_sels(node, data_mask, context_mask, init = init)
 18. tidyselect:::walk_data_tree(new, data_mask, context_mask)
 19. tidyselect:::as_indices_sel_impl(...)
 20. tidyselect:::as_indices_impl(x, vars, strict = strict)
 21. tidyselect:::chr_as_locations(x, vars)
 22. vctrs::vec_as_location(x, n = length(vars), names = vars)
 24. vctrs:::stop_subscript_oob(...)
 25. vctrs:::stop_subscript(...)

Thanks

**Comment by thierrygosselin** [comment] 2021-01-11 17:09
@tpfeilsticker The problem is that I can reproduce the error you're getting. Open a separate issue following guidelines.
My guess is that the tidy data just as `GT_BIN` in it.

You could try this:

```
new.tidy.data <- radiator::calibrate_alleles(data = t_genpop) # if t_genpop is a tidy dataset in the global env.
```

Then:
```
radiator::write_genepop(data = new.tidy.data)
```

Or use from the start `radiator::genomic_converter` that will detect the output you requested and generate the appropriate genotype format it needs.

**Comment by thierrygosselin** [comment] 2021-01-11 17:10
Hi Carly @cgraham13 could you send me the necessary files to reproduce the problem, with my datasets I unfortunately can't...

Best
Thierry

**Comment by thierrygosselin** [comment] 2021-06-16 07:00
Fixed with latest version

**Closed by thierrygosselin** 2021-06-16 07:00 UTC
