### ISSUE TITLE
Bug in sexy_markers?

### ISSUE THREAD

**Issue by sarahwhiteley** [thierrygosselin/radiator#51] opened 2019-07-09 06:14 UTC
Hi,

I have just started using your package to try to identify sex linked markers in a DArT dataset, and have run into problems with the "sexy_markers" function. I am sure this is probably due to my own incompetence, but as this is quite a new package I quickly ran into a dead end for troubleshooting short of pestering you here, so I apologise.  

I created a "strata" file (individual IDs from Dart file + "strata", which is sex - M, F, U in this case) and have a csv file from Dart. I ran the following code using these two files

sexy_markers("Report_DAmh19-4061_SNP_2", strata = AM_STRATA.tsv, filters = TRUE)

and received the following error 

Execution date@time: 20190709@1555
Folder created: sexy_markers_20190709@1555
File written: radiator_sexy_markers_args_20190709@1555.tsv
Error in file(con, "r") : cannot open the connection

Computation time, overall: 0 sec
############################ sexy markers completed #############################

Do you have any suggestions as to how I can resolve this issue?

Thanks! 

- Session info ------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.5.3 (2019-03-11)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_Australia.1252      
 ctype    English_Australia.1252      
 tz       Australia/Sydney            
 date     2019-07-09

**Comment by thierrygosselin** [comment] 2019-08-08 19:04
Hi Sarah, 
Sorry for the response delay.
Was away from computer.

If the issue is still relevant, could you send an email with data + strata so that I try to reproduce the bug you're having.

Best
Thierry

**Comment by FloriaanDD** [comment] 2019-08-08 23:55
Dear Sarah,
As Thierry mentioned, it may be easier to reproduce the bug with your data. 

However, the 'cannot open the connection' error usually reflects and error with the input data or the working directory. I see that the data argument is missing the ".csv" extension and the strata argument is not between quotations, Perhaps you could try set the working directory to the folder with your data and strata files and run this code: 
results <- sexy_markers(data = "Report_DAmh19-4061_SNP_2.csv", strata = "AM_STRATA.tsv", filters = TRUE)

I hope this helps.
Cheers,
Floriaan

**Comment by sarahwhiteley** [comment] 2019-08-09 02:32
Hi,

Thanks for getting back to me. I tried the following code

library(dartR)
install.packages("remotes")
remotes::install_github("thierrygosselin/radiator")
library(radiator)

setwd("C:/Users/s437549/OneDrive - University of Canberra/A. muricatus/DART/AMDart") ### This is the project directory – just put it here in case it has some bearing on the issue#

AMSTRATA <- read.delim("AM_STRATA.tsv.txt", stringsAsFactors=FALSE, row.names = 1)

AMGL<- test(filename = "Report_DAmh19-4061_SNP_2.csv", topskip=6, nmetavar=30, ind.metafile = "AMDart_metadata.csv")

results<- sexy_markers(data="Report_DAmh19-4061_SNP_2.csv", strata = "AM_STRATA.tsv", filters = TRUE)

And still received a different error

Execution date@time: 20190809@1126
Folder created: sexy_markers_20190809@1126
File written: radiator_sexy_markers_args_20190809@1126.tsv
Reading DArT file...
Error:
strata file doesn't exist...

Call `rlang::last_error()` to see a backtrace

DArT conversion timing: 0 sec

Computation time, overall: 0 sec
############################ sexy markers completed #############################

This seemed like an issue with recognising the file names due to me renaming them when I read the data in, so I also tried

results<- sexy_markers(data="AMGL", strata = "AMSTRATA", filters = TRUE)

But then am back to the original connection error.


Execution date@time: 20190809@1127

Folder created: sexy_markers_20190809@1127

File written: radiator_sexy_markers_args_20190809@1127.tsv

Error in file(con, "r") : cannot open the connection



Computation time, overall: 0 sec

############################ sexy markers completed #############################

**Comment by FloriaanDD** [comment] 2019-08-09 04:08
Hi Sarah,
It seems to me that the name for the strata argument changed from""AM_STRATA.tsv" to "AM_STRATA.tsv.txt"?
So you may want to try:
 results<- sexy_markers(data="Report_DAmh19-4061_SNP_2.csv", strata = "AM_STRATA.tsv.txt", filters = TRUE)
Please note that you need 3 columns in your strata file with the following colnames: "INDIVIDUALS" (the names of each individual), TARGET_ID (the unique identifier DArT assigns to each individual; this is a number that can be found in the DArT data file. Row 7 in your case) and STRATA (The sex ID).

It may be easier to send your data and strata files to have a better grasp on the problem.
Thanks!
Floriaan

**Comment by sarahwhiteley** [comment] 2019-08-09 06:10
Hi Floriaan,

Sorry for being so dense. I have fixed those issues – I didn’t realise I needed a “TARGET_ID” column, so I added that. However, these IDs are the same at the “INDIVIDUALS” which I thought was causing issues, so I tested making them unique but still ran into the following issue so it didn’t seem to make a difference

Execution date@time: 20190809@1555
Folder created: sexy_markers_20190809@1555
File written: radiator_sexy_markers_args_20190809@1555.tsv
Reading DArT file...
Error in `$<-.data.frame`(`*tmp*`, "INDIVIDUALS", value = character(0)) :
  replacement has 0 rows, data has 91
In addition: Warning message:
Unknown or uninitialised column: 'INDIVIDUALS'.

DArT conversion timing: 0 sec

Computation time, overall: 0 sec
############################ sexy markers completed #############################

Is this because it’s trying to find “INDIVIDUALS” in the Dart file? Was I supposed to make adjustments in that file?

My strata file is attached, but my dart file is too large (however it is just the usual file you get from Dart – I haven’t done anything to it). I’m not sure if this will work but try this link
https://ucstaff-my.sharepoint.com/:x:/g/personal/sarah_whiteley_canberra_edu_au1/ET0a1xExDGRJoyW2rlwozr8BuIf_asz0dOFtAIYEixJovw?e=kT601X

I’m so sorry to keep pestering you and thank you so much for your patience!

Sarah

**Comment by FloriaanDD** [comment] 2019-08-09 06:17
Hi Sarah,
The first column of your strata file is named "INDIVIDUAL" and not "INDIVIDUALS".
Perhaps this will solve the issue.
I couldn't download the DArT file though.
Cheers,
Floriaan

**Comment by sarahwhiteley** [comment] 2019-08-09 06:45
Far out my attention to detail is seriously lacking! Sorry!!

Ok so its working now, but stalls at a certain point with the following error

Error in .DynamicClusterCall(cl, length(cl), .fun = function(.proc_idx,  :
  One of the nodes produced an error: Can not open file 'C:\Users\s437549\OneDrive - University of Canberra\A. muricatus\DART\AMDart\sexy_markers_20190809@1625\radiator_20190809@1625.gds.rad'. The process cannot access the file because it is being used by another process.

Computation time, overall: 9 sec
############################# completed filter_ld ##############################

Computation time, overall: 73 sec
############################ sexy markers completed #############################

My working directory usually automatically syncs to the cloud, so I thought perhaps that was causing issues, so stopped syncing but still have this error. I also tried restarting my whole computer and only opening R and it still happens. I have no idea what other process could be using the file.

It is producing 2 folders in my working directory - I was wondering if there was a way to manually step back into the processes by adding in the files it wants?

Again, thank you for your patience – as I’m sure you’re painfully aware I am not that great with R.

Thanks

Sarah

**Comment by FloriaanDD** [comment] 2019-08-09 06:52
Hmm, This one may be more difficult to solve.
Either, your OneDrive/PC settings is not allowing the created files to be over-written.
Or, the windows clusters are not working well together.
I suggest to first try setting the 'parallel.core' to 1:
results<- sexy_markers(data="Report_DAmh19-4061_SNP_2.csv", strata = "AM_STRATA.tsv.txt", filters = TRUE, parallel.core = 1).
Let me know how that goes.
Cheers,
Floriaan

**Comment by sarahwhiteley** [comment] 2019-08-11 23:05
Step 4. Threshold selection
Look at the boxplot, a threshold of 0.2 blacklist more markers than 0.8

Enter the long LD threshold (filter.long.ld threshold, double/proportion):
0.1
Pruning with SNPRelate...
SNV pruning based on LD:
Calculating allele counts/frequencies ...
[==================================================] 100%, completed in 14s
Working space: 87 samples, 71,951 SNVs
    using 1 (CPU) core
    sliding window: 500,000 basepairs, Inf SNPs
    |LD| threshold: 0.1
    method: R
Error in SNPRelate::snpgdsLDpruning(gdsobj = data, snp.id = wl$VARIANT_ID,  :
  INTEGER() can only be applied to a 'integer', not a 'character'

Computation time, overall: 27 sec
############################# completed filter_ld ##############################

Computation time, overall: 593 sec
############################ sexy markers completed #############################

Thanks Floriaan, that did help and I think nearly the whole function ran but unfortunately ran into the above issue right at the end. Any suggestions?

Cheers,

Sarah

**Comment by FloriaanDD** [comment] 2019-08-12 00:52
Hi Sarah,
I believe it is unnecessary to filter on long distance LD to find sex-linked markers. Especially since markers on the W or Y chromosome will show the same pattern of inheritance and you would be deleting all your informative markers. For example, I have found Y-linked markers that were less than 1kb apart. These would have been filtered out with the long LD filter. However, we keep this filtering function for really problematic datasets, but in my experience, DArT has good quality data.

Nonetheless, this error is important for other applications. We can look into this error, but we would need your dataset. to see if it is a bug in the 'filter_LD' function or in your data.
Please run the 'sexy_markers' function again without long LD filtering and let me know if it worked. Then I can close this thread.
Many thanks!
Floriaan

**Comment by sarahwhiteley** [comment] 2019-08-12 03:15
Hi Floriaan,

Not filtering on long distance LD allowed the function to move past that error. I was unsure if filtering using the P/A and heterozygosity parameters were necessary – the graphs it generated are attached if that helps.

I chose not to filter on either because I didn’t understand what they would do, and I ran into a different error. Is this potentially because I was supposed to filter on at least one of those parameters?

Do you want to continue filtering using long distance ld  ? (y/n):
n

Computation time, overall: 25 sec
############################# completed filter_ld ##############################


Sex-ratio (F/M): 1.16
Your data does not have Read Depth information; the analysis based on Read Depth will not be performed
Files written: '1A.sexy_markers_PA_scatter_plot.pdf' & '1B.sexy_markers_PA_tuckey_plot.pdf'
P/A method of SNPs:
Look at the figures: Do you want to filter the data (y/n):
n
Files written: 'sexy_markers_HET_scat_plot.pdf' & 'sexy_markers_HET_qr_plot.pdf'
Heterozygosity method of SNPs:
Look at the figures: Do you want to filter the data (y/n):
n
Error: All columns in a tibble must be 1d or 2d objects:
* Column `SEX_MARKERS` is NULL
Call `rlang::last_error()` to see a backtrace

Computation time, overall: 256 sec
############################ sexy markers completed #############################

Thank you so  much for your help and patience! Sorry if you already received this – outlook is playing up. It’s not letting me attach my graphs so if you need those and/or my Dart file let me know and I’ll figure out how to share them with you.

Cheers,

Sarah

**Comment by FloriaanDD** [comment] 2019-08-12 03:21
Hi Sarah,
The presence-absence, heterozygosity and coverage graphs are different methods to detect either Y/W- or X/Z-linked markers. These methods are described in the function documentation.
Best, 
Floriaan

**Comment by sarahwhiteley** [comment] 2019-08-12 03:29
Hi Floriaan,

Thanks for that I’ll read through it. Thank you so much for your help and I apologise for pestering you so much. You can go ahead and close the thread on github.

Thanks again,

Sarah

**Closed** 2019-08-12 03:54 UTC

**Comment by FloriaanDD** [comment] 2019-08-12 08:36
Pff… That was quite an effort to get this girl sorted out :p

Could we have a chat sometime about potential bugs, such as the ‘read_vcf’?
Cheers,
Floriaan
