### ISSUE TITLE
fis_summary inoperable

### ISSUE THREAD

**Issue by shofmon88** [thierrygosselin/radiator#23] opened 2018-08-08 02:49 UTC
Attempting to run fis_summary on either a tidy or genlight object returns an error.

fis.test <- fis_summary(tidy.final, vcf.metadata = FALSE)
#######################################################################
#######################################################################
Error in radiator::tidy_genomic_data(data = data, vcf.metadata = TRUE,  : 
  Unknowned "..." parameters maf.pop.num.threshold maf.approach maf.operator

Variations of the above code were used with identical results.

**Comment by thierrygosselin** [comment] 2018-08-15 15:27
thanks for reporting the issue, it's an old function, will check the problem and report a fix within the next 2 days

**Comment by thierrygosselin** [comment] 2018-08-18 04:05
the issue is resolved in the latest release
You can also have more interesting info for FIS and HET in `detect_het_outliers`

**Closed by thierrygosselin** 2018-08-18 04:05 UTC
