### ISSUE TITLE
Fatal error when blacklist is included

### ISSUE THREAD

**Issue by amybwelsh** [thierrygosselin/radiator#24] opened 2018-08-11 00:03 UTC
Hi Thierry!  When I try to run genomic_converter with blacklist.id, I get a fatal error and RStudio shuts down. It seems to be able to read the file because it says there are 11 individuals in the file (which is correct), but after it reads the loci and says Done, the fatal error occurs.  I've run genomic_converter without blacklist.id and it works fine so there seems to be an issue with the blacklist.id.

**Comment by thierrygosselin** [comment] 2018-08-15 15:29
Hi Amy, sorry for the delay, currently on vacations
The function with a blacklist works fine on my end, could you provide the output of 
```
devtools::session_info()
```

and provide the first 5 or 10 id in the blacklist please ?

**Comment by amybwelsh** [comment] 2018-08-16 12:36
Hi Thierry,

I don’t get much when I request session info.  I think it’s because the session gets aborted when I run it with the blacklist and RStudio shuts down.  When I ask for session info, I get the setting, version, system, ui, language, etc., and a list of packages.  Is that what you needed?  I’ve also attached the blacklist file.  I’m using the one that was generated through missing_visualization.  This is what I type in when I run it.  It works if I don’t include the blacklist.id.

stlaw <- genomic_converter(data = “populations.snps.vcf”, output = c(“genepop”), strata = “StLaw_popmap.txt”, blacklist.id = “blacklist.id.missing.50.tsv”)

Thanks,
Amy

Amy B. Welsh, Ph.D.
Associate Professor
West Virginia University
School of Natural Resources
P.O. Box 6125
Morgantown, WV 26506
Office: 311B Percival Hall
Phone: 304-293-0718
Website: http://wildgenomics.forestry.wvu.edu/

**Comment by thierrygosselin** [comment] 2018-08-16 23:36
Hi Amy,
yes copy/paste what is outputted by ``devtools::session_info()`

Very difficult for me to recreate the bug without at least the blacklist of id (I don't see it attached here, so email it to me thierrygosselin@icloud.com.

First thing you could check is:

Usually one of the problem encountered is the end of line generated by Windows.
Check with a text editor or free software like flip`https://ccrma.stanford.edu/~craig/utility/flip/` that the line ending are UNIX (LF).

**Comment by thierrygosselin** [comment] 2018-08-17 15:39
integers, I see 
probably a problem with character/integer recognition (it's usually character).
will fix this morning

**Comment by thierrygosselin** [comment] 2018-08-18 04:07
issue resolved in the latest release
thanks for reporting

**Comment by amybwelsh** [comment] 2018-08-20 14:14
Thanks, Thierry!!

Amy B. Welsh, Ph.D.
Associate Professor
West Virginia University
School of Natural Resources
P.O. Box 6125
Morgantown, WV 26506
Office: 311B Percival Hall
Phone: 304-293-0718
Website: http://wildgenomics.forestry.wvu.edu/

**Comment by amybwelsh** [comment] 2018-08-28 15:36
Hi Theirry,

I finally got around to trying it.  I installed your latest release and I’m having the same problem. ☹

Thanks,
Amy

Amy B. Welsh, Ph.D.
Associate Professor
West Virginia University
School of Natural Resources
P.O. Box 6125
Morgantown, WV 26506
Office: 311B Percival Hall
Phone: 304-293-0718
Website: http://wildgenomics.forestry.wvu.edu/

**Comment by thierrygosselin** [comment] 2018-08-28 16:57
Hi Amy,

I'm not able to reproduce the bug with data at hand, could you email me everything that I need to reproduce the error: all the files and command.

Best,
Thierry

**Comment by amybwelsh** [comment] 2018-08-28 17:48
Hi Thierry,

I just sent you a Dropbox link to the files I’m using.  I sent it to your icloud email.  Below is the R command I’m using:

stlaw <- genomic_converter(data = “populations.snps.vcf”, output = c(“genind”, “genepop”, “structure”, “bayescan”), strata = “StLaw_popmap.txt”, blacklist.id = “blacklist.id.missing.50.tsv”, imputation.method = “rf”)

Thanks!
Amy

Amy B. Welsh, Ph.D.
Associate Professor
West Virginia University
School of Natural Resources
P.O. Box 6125
Morgantown, WV 26506
Office: 311B Percival Hall
Phone: 304-293-0718
Website: http://wildgenomics.forestry.wvu.edu/

**Comment by thierrygosselin** [comment] 2018-09-04 06:49
Should work with radiator v.0.0.16
it should be much faster too...

**Closed by thierrygosselin** 2018-09-04 06:49 UTC
